import { StyleSheet } from "react-native";
import { C } from "../utils/color";

export const stylesMetrics = StyleSheet.create({
  screen: { flex: 1, backgroundColor: C.white },
  screenContent: { padding: 16, gap: 24, paddingBottom: 40 },

  h1: { color: C.gray900, fontSize: 20, fontWeight: "700" },
  h1Subtitle: { color: C.gray500, fontSize: 14, marginTop: 2 },

  emptyState: { alignItems: "center", justifyContent: "center", paddingVertical: 80, gap: 16 },
  emptyIconBadge: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: C.purple50,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyTitle: { color: C.gray800, fontWeight: "600", fontSize: 16 },
  emptySubtitle: { color: C.gray400, fontSize: 14, marginTop: 4, textAlign: "center", maxWidth: 260 },
  primaryButton: {
    marginTop: 4,
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: C.purple600,
    borderRadius: 12,
  },
  primaryButtonText: { color: C.white, fontSize: 14, fontWeight: "500" },

  loadingBox: { alignItems: "center", justifyContent: "center", paddingVertical: 80 },

  errorBox: {
    backgroundColor: C.rose50,
    borderWidth: 1,
    borderColor: C.rose200,
    borderRadius: 16,
    padding: 16,
  },
  errorText: { color: C.rose600, fontSize: 14 },

  banner: { backgroundColor: C.indigo700, borderRadius: 16, padding: 20 },
  bannerTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.15)",
  },
  bannerLabel: {
    color: C.purple200,
    fontSize: 11,
    fontWeight: "500",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  bannerValue: { fontSize: 28, fontWeight: "700" },
  bannerSubValue: { color: C.purple200, fontSize: 13, marginTop: 2 },
  bannerPeriodValue: { color: C.white, fontSize: 17, fontWeight: "700" },
  bannerGrid: { flexDirection: "row", flexWrap: "wrap", gap: 16 },
  bannerGridItem: { width: "45%" },
  bannerGridValue: { color: C.white, fontWeight: "700", fontSize: 14 },

  sectionTitle: { color: C.gray400, fontSize: 10, textTransform: "uppercase", letterSpacing: 1, fontWeight: "500" },
  sectionSubtitle: { color: C.gray400, fontSize: 12 },

  cardGrid: { flexDirection: "row", flexWrap: "wrap", gap: 16, marginTop: 12 },
  cardGridItem: { width: "100%" },
  cardGridItemFull: { width: "100%" },

  card: {
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.gray100,
    borderRadius: 16,
    padding: 20,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  cardTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 12 },
  iconBadge: { width: 36, height: 36, borderRadius: 12, alignItems: "center", justifyContent: "center" },
  rowGap: { flexDirection: "row", alignItems: "center", gap: 8 },
  tagBadge: { backgroundColor: C.gray100, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 2 },
  tagBadgeText: { color: C.gray400, fontSize: 9, fontWeight: "500" },
  cardLabel: { color: C.gray400, fontSize: 12, fontWeight: "500", textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 4 },
  cardValue: { fontSize: 24, fontWeight: "700" },
  cardSubtitle: { color: C.gray400, fontSize: 12, marginTop: 2 },
  tooltip: {
    position: "absolute",
    bottom: "100%",
    left: 0,
    marginBottom: 8,
    zIndex: 10,
    backgroundColor: C.gray900,
    borderRadius: 12,
    padding: 12,
    width: 240,
  },
  tooltipText: { color: C.white, fontSize: 12, lineHeight: 18 },

  chartCard: {
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.gray100,
    borderRadius: 16,
    padding: 16,
  },

  noSellsBox: {
    backgroundColor: C.white,
    borderWidth: 1,
    borderColor: C.gray100,
    borderRadius: 16,
    padding: 32,
    alignItems: "center",
    gap: 12,
  },
  noSellsIconBadge: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: C.purple50,
    alignItems: "center",
    justifyContent: "center",
  },
  noSellsTitle: { color: C.gray800, fontWeight: "600", fontSize: 14 },
  noSellsSubtitle: { color: C.gray400, fontSize: 12, marginTop: 4, textAlign: "center", maxWidth: 280, lineHeight: 18 },

  noteBox: {
    backgroundColor: C.amber50,
    borderWidth: 1,
    borderColor: C.amber100,
    borderRadius: 16,
    padding: 16,
    flexDirection: "row",
    gap: 12,
  },
  noteText: { color: C.amber700, fontSize: 12, lineHeight: 18, flex: 1 },
  noteTextBold: { fontWeight: "700" },
});